language: ruby
rvm:
  - 2.3.1
env:
  - CODECLIMATE_REPO_TOKEN: 6e0c92d69173395e9099d2fa52374fa6c37bcc1e1be3fe3247d61fa2432de1b6
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  slack: navyblue-team:ioO5diAGc5WUQVDKc5BH1UbE
  email: false